<?php
echo "<H1>WILL YOU BE OK TOMORROW?</H1>";
echo "<H1>WILL YOU BE OK TOMORROW AGAGIN?</H1>";
echo "<H1>WILL YOU BE OK TOMORROW?</H1>";
echo "<H1>WILL YOU BE OK TOMORROW AGAGIN?</H1>";
echo "<H1>WILL YOU BE OK TOMORROW DEC 20?</H1>";
echo "<H1>WILL YOU BE OK TOMORROW 11111?</H1>";
?>
